### PR TITLE
ecs-update - Always quote the added changelog version

### PR DESCRIPTION
**Pull request by andrewkroh**
Like it says. See test case.

### CODE REVIEW

**Review by taylor-swanson — APPROVED** [review]
LGTM

**Comment by efd6** [comment]
Why do we need to do this?

**Comment by andrewkroh** [comment]
My only justification is to follow what `elastic-package changelog add` would do.

https://github.com/elastic/elastic-package/blob/1680d755cf3260b0adaa88323185462115ce53e9/internal/packages/changelog/yaml.go#L69

**Comment by efd6** [comment]
That's unfortunate. Ideally, ep would be fixed.

**Comment by andrewkroh** [comment]
Logged https://github.com/elastic/elastic-package/issues/1466 for adding that merge behavior for unreleased changes.

**Pull request merged**
